version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"    # MQTT TCP
      - "8081:8081"    # MQTT WebSocket
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./logs:/mosquitto/log
    restart: unless-stopped
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer:latest
    container_name: mqtt-explorer
    ports:
      - "4000:4000"
    depends_on:
      - mosquitto
    restart: unless-stopped

  detector:
    build: .
    container_name: detector_colisao
    depends_on:
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"   # Porta do Flask para o navegador
    restart: unless-stopped
    command: ["python", "web_server.py"]  # executa o site + detector
